Homework/roman/task 03
aodarc/lits-13 pull request #2
Opened 2020-05-03 19:43 UTC by sharamaga

Homework task 3 completed

Roman

2020-05-04 12:33 UTC, aodarc requested changes

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    """ Make all lower case"""
Тільки верхній рядок рахується за документацію функції яка повинна бути описати на потрійних кавичках.
Всі решта коментарі не потрібно огортати кавичками, їх слід писати як звичайний коментар.
`""" Remove white spaces """` -> `# Remove white spaces`

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    loc_str = (str(in_data)).lower()
Можна не брати в додаткові дужки
`(str(in_data)).lower()` -> `str(in_data).lower()`

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    loc_str = (str(in_data)).lower()
+ це все можна ще й об'єднати з наступною дією
додай в ланцюжок `.replace(' ', '')`

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    if loc_str[0:int(len(loc_str) / 2):1] == loc_str[-1:-(int(len(loc_str) / 2) + 1):-1]:
Якщо подивитися з далеку `(int(len(loc_str) / 2)` повторіюється, хоча і повертає один і той же результат. Її було б добре винести в окрему константу, щоб не робити цю операцію двічі

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    pass
pass - пишуть коли функція чи метод порожні. Його можна прибрати

2020-05-04 12:33 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +
Можеш спробувати ще один солюшин, щоб не порівнювати половини слова, його можна просто розвернути задом на перед. Типу реверснути

2020-05-04 16:01 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +    loc_str = (str(in_data)).lower()
> 
> 
> Можна не брати в додаткові дужки
> `(str(in_data)).lower()` -> `str(in_data).lower()`
Ооо,  то не просто відмовитись від дужок, в С дужки то наше всьо, дужок багато не буває :-) Буду старатись

2020-05-04 16:02 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +    if loc_str[0:int(len(loc_str) / 2):1] == loc_str[-1:-(int(len(loc_str) / 2) + 1):-1]:
Згоден, я просто до оптимізації не дойшов, аби запрацювало. Зроблю.

2020-05-04 16:10 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +    pass
Це просто артефак прокрався якимось чудом, пофіксаю

2020-05-04 16:33 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +
Пропозицію розумію, є питання стосовно реалізації, це реалізувати додатково до існуючої чи замість?

2020-05-04 19:20 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +    """ Make all lower case"""
Ok, пофіксаю

2020-05-04 19:37 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +
Реалізував замість

2020-05-05 09:48 UTC, aodarc requested changes

2020-05-05 09:48 UTC, aodarc commented on homework/Roman/task_03/task_03.py
> +    if loc_str[0:str_length] == loc_str[-1:-str_length - 1:-1]:
Такс вчимося спрощувати слайси
`loc_str[0:str_length]` -> `loc_str[:str_length]` -> `loc_str[::]` -> `loc_str[:]` -> `loc_str` - це все поверне один і той самий результат. Коли є квадратні дужки з просто `:` воно бере аргументи за замовчуванням - кінець і почато колекції.

`loc_str[-1:-str_length - 1:-1]` -> `loc_str[::-1]` аналогічно ми пробігаємо по колекції з початку до кінця, зі зворотнім кроком. Тому це просто реверс.

2020-05-06 15:15 UTC, sharamaga commented on homework/Roman/task_03/task_03.py
> +    if loc_str[0:str_length] == loc_str[-1:-str_length - 1:-1]:
Зрозуміло, спростив.

2020-05-18 14:08 UTC, aodarc approved these changes

2020-06-09 09:36 UTC, merged