Homework/roman/task 04
aodarc/lits-13 pull request #3
Opened 2020-05-03 19:44 UTC by sharamaga

Homework task 4 completed

Roman

2020-05-04 12:42 UTC, aodarc requested changes

2020-05-04 12:42 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    """ Need special care for negatives """
Те саме зауваження що в завданні №2

2020-05-04 12:42 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    if type(in_data) is float:
для перевірки приналежності типу слід використовувати `isinstance(obj, type)`

2020-05-04 12:42 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    def calc(text: str):
Можна обійтися без вкладеної функції, для того спочатку слід зробити всі необхідні перевірки, якщо їх проходить дата, тоді просто обчистили результат

2020-05-04 12:42 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +            if i == '9':
ці всі іфчики потрібно переписати через `dict` як то кажуть більше ніж три іфа то індусокод.
в дікті діставати по ключу швидше ніж обчислювати іфчик. Тому ключами треба дати цифри, а значеннями, я думаю здогадалися всі) + якщо використовувати дефолтні значення в дікті то кількість його ключів можна скоротити з 10 до 4

2020-05-04 19:41 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +    """ Need special care for negatives """
В завданні 2 не було ніяких коментарів. Ви певно про стиль коментірв, поправлю

2020-05-04 19:41 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +    if type(in_data) is float:
А чому?

2020-05-04 20:06 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +    if type(in_data) is float:
Знайшов в неті, is не враховує наслідування.

2020-05-04 20:07 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +    def calc(text: str):
Добре, перероблю.

2020-05-04 20:07 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +            if i == '9':
Перероблю.

2020-05-05 09:53 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    if type(in_data) is float:
`is` використовується для перевірки ідентичності Об'єктів. Грубо кажучи перевіряє чи збігаються вони по адресах пам'яті, аьо кажучи простіше по `id(obj)`.
`type(in_data) is float` тут якщо читати по зміїному: "чи клас об'єкту in_data це той самий об'єкт, що і клас `float`" так type() поверне той самий об'єкт що і тип тип float. Але ми ж перевіряємо чи in_data є об'єктом (інстансом) float. Ну з точки зору читабельності і логіки коду. Результат той самий але прийнято перевіряти через isinstance

2020-05-05 09:58 UTC, aodarc approved these changes

2020-05-05 09:58 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    d = {'9': 1, '8': 2, '7': 0, '6': 1, '5': 0, '4': 1, '3': 0, '2': 0, '1': 0, '0': 1, '-': 0}
Виглядає вже краще) але це можна ще більше спростити

```
d = {
   '0': 1,
   '4': 1,
   '6': 1,
   '8': 2,
   '9': 1,
}
cnt = 0
for number in str(in_data):
    cnt += d.get(number)
```

2020-05-06 15:24 UTC, sharamaga commented on homework/Roman/task_04/task_04.py
> +    d = {'9': 1, '8': 2, '7': 0, '6': 1, '5': 0, '4': 1, '3': 0, '2': 0, '1': 0, '0': 1, '-': 0}
Зменшити уількість елементів в словнику не вийде - буде доступ по неіснуючому ключу.

2020-05-18 14:10 UTC, aodarc commented on homework/Roman/task_04/task_04.py
> +    d = {'9': 1, '8': 2, '7': 0, '6': 1, '5': 0, '4': 1, '3': 0, '2': 0, '1': 0, '0': 1, '-': 0}
в тому то і суть. що є safe метод get() який повертає дефолтне значення, якщо немає такого ключа

2020-06-09 09:36 UTC, merged